dist: xenial
language: python

python:
  - "3.6"

branches:
  only:
    - gabriel#15
    - dev
    - master

env:
  - DJANGO=2.2 DB=sqlite

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install psycopg2-binary

before_script:
  - echo "SECRET_KEY=$SECRET_KEY" >> .env
  - echo "DB_NAME = 'travis_ci_db'" >> .env
  - echo "DB_USER = 'gag'" >> .env
  - echo "DB_PASSWORD =$DB_PASSWORD" >> .env
  - echo "DB_HOST = 'localhost' " >> .env
  - echo "DB_PORT = '' " >> .env

  - sqlite3 --version
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - python manage.py test
