language: python

python:
  - "3.6"

services: mysql

branches:
  only:
    - gabriel#15
    - dev
    - master

env:
  - DJANGO=2.2

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

before_script:
  - echo "SECRET_KEY=$SECRET_KEY" >> .env
  - echo "DB_NAME = 'travis_ci_db'" >> .env
  - echo "DB_USER = 'gag'" >> .env
  - echo "DB_PASSWORD =$DB_PASSWORD" >> .env
  - echo "DB_HOST = 'localhost' " >> .env
  - echo "DB_PORT = '' " >> .env

  - mysql -e 'create database travis_ci_db;'
  - python sgpg/manage.py makemigrations
  - python sgpg/manage.py migrate

script:
  - python sgpg/manage.py test