# Generated by Django 2.2.1 on 2019-05-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='identificador',
            field=models.CharField(default='ufpi_computacao', max_length=255),
            preserve_default=False,
        ),
    ]
